# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
defaults:
  run:
    shell: bash
    working-directory: ./
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        make install

    - name: Run tests
      run: |
        make test
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        name: codecov
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true